### ISSUE TITLE
How to setup this project

### ISSUE THREAD

**Issue by VN0** [yashjoshi007/Music_player#1]
### Where did I make a mistake? Please help me.

P.S. Can you implement the ability to attach a cover to a track?

**Comment by yashjoshi007** [comment]
no , it will download .mp3 i tried it on various devices it did worked

**Comment by VN0** [comment]
Ok. How to configure it so that it works with my firebase account?

**Comment by yashjoshi007** [comment]
Just , include firebase assistant to your app directly or from the account
, thats it , just give it storage acceptance . And its done .

**Comment by VN0** [comment]
Thanks, but after I did it didn't work!

**Comment by yashjoshi007** [comment]
Sorry , but could not help 👍🏻
